
export enum Env {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  FILES_DEST = 'FILES_DEST',
  MAX_FILE_SIZE = 'MAX_FILE_SIZE'
}

export enum NodeEnvValues {
  prod = 'production',
  dev = 'development',
  test = 'test'
}
